version: "3.9"
services:
  user_db:
    image: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready"]
      timeout: 1s
      retries: 0
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: "host"
  user_login:
    build: .
    depends_on:
      user_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    network_mode: "host"
volumes:
  postgres:
