---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-configuration
  labels:
    app: fiufit
    tier: users-microservice
data:
  USERS_DB_HOST: dpg-cikrbnlph6eg6ke1cgbg-a.oregon-postgres.render.com
  USERS_DB_DATABASE: fiufit_4evp
  USERS_DB_USER: "fiufit"
  USERS_DB_PASSWORD: $USERS_DB_PASSWORD
  USERS_LOG_LEVEL: INFO
  USERS_AUTH_HOST: auth-service.taller2-marianocinalli.svc.cluster.local:8002
  USERS_TEST_IS_TESTING: "False"
  USERS_PAYMENTS_HOST: payment-service.taller2-marianocinalli.svc.cluster.local:8020
  USERS_MONGO_HOST: fiufit.rqnbyme.mongodb.net
  USERS_MONGO_DRIVER: mongodb+srv
  USERS_MONGO_PASSWORD: $USERS_MONGO_PASSWORD
  USERS_REDIS_HOST: "redis-master.taller2-marianocinalli.svc.cluster.local"
  NEW_RELIC_LICENSE_KEY: $USERS_NEW_RELIC_KEY
  NEW_RELIC_APP_NAME: users
  NEW_RELIC_MONITOR_MODE: "true"
  NEW_RELIC_LOG: stderr
  NEW_RELIC_LOG_LEVEL: warning
