---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-configuration
  namespace: taller2-marianocinalli
  labels:
    app: fiufit
    tier: users-microservice
data:
  USERS_DB_DATABASE: "fiufit"
  USERS_DB_USER: "backend"
  USERS_DB_HOST: "dpg-cgno8m8rddl9mmvdaja0-a.oregon-postgres.render.com"
