---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: taller2-marianocinalli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: marianocinalli/users:latest
