---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: taller2-marianocinalli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: marianocinalli/users:latest
        ports:
        - containerPort: 8000
          name: users-svc
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
