---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: fiufit
    tier: users-service
spec:
  type: ClusterIP
  ports:
  - name: users-svc
    protocol: TCP
    port: 8000
    targetPort: http-users
  selector:
    app: fiufit
    tier: users-microservice
